title: mc-iam-manager
description: docs for mc-iam-manager
theme: just-the-docs

url: https://mzc-csc.github.io/mc-iam-manager/

aux_links:
  Github: https://github.com/m-cmp/mc-iam-manager

# color_scheme: dark
