title: mc-iam-manager
description: docs for mc-iam-manager
theme: just-the-docs

url: https://mzc-csc.github.io/mc-iam-manager/

aux_links:
  Github: https://github.com/m-cmp/mc-iam-manager


nav_external_links:
  - title: API Docs (swagger)
    url: /mc-iam-manager/swagger/index.html