title: mc-iam-manager
description: docs for mc-iam-manager
theme: just-the-docs

url: https://mzc-csc.github.io/mc-iam-manager

aux_links:
  Github: https://github.com/m-cmp/mc-iam-manager


nav_external_links:
  - title: API Docs (swagger)
    url: https://m-cmp.github.io/mc-iam-manager/swagger/


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red