services:

  # Certbot (인증서 발급 및 갱신용)
  # 이 컨테이너는 필요할 때만 1회성으로 실행됩니다.
  mcmp-certbot:
    image: certbot/certbot:latest
    container_name: mcmp-certbot
    volumes:
      - ./container-volume/mc-iam-manager/certs:/etc/letsencrypt
      - ./container-volume/certbot/www:/var/www/certbot
    networks:
      - mc-iam-manager-network
    entrypoint: ["certbot"]
    command: ["certonly", "--webroot", "--webroot-path", "/var/www/certbot",
              "--email", "${MC_IAM_MANAGER_CERT_EMAIL}",
              "--agree-tos", "--no-eff-email",
              "-d", "${MC_IAM_MANAGER_PUBLIC_DOMAIN}",
              "--non-interactive"]

networks:
  mc-iam-manager-network:
    external: true
    name: mc-iam-manager_mc-iam-manager-network