# Stage1: build
FROM quay.io/keycloak/keycloak:24.0.4 as builder

WORKDIR /opt/keycloak

RUN keytool -genkeypair -storepass password123 -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

# Stage2: deploy
FROM quay.io/keycloak/keycloak:24.0.4

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_HEALTH_ENABLED=true

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]