/*
 * MCIAMManager API 명세서
 *
 * MCIAMManager API 명세서
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iammodels

type UserInfo struct {
	Id            string              `json:"Id,omitempty"`
	UserId        string              `json:"userId,omitempty"`
	UserName      string              `json:"userName,omitempty"`
	Email         string              `json:"email,omitempty"`
	UserRoleList  []UserRoleInfo      `json:"userRoleList,omitempty"`
	WorkspaceList []UserWorkspaceInfo `json:"workspaceList,omitempty"`
}
