/*
 * MCIAMManager API 명세서
 *
 * MCIAMManager API 명세서
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iammodels

type RoleInfo struct {
	RoleId             string              `json:"roleId,omitempty"`
	RoleName           string              `json:"roleName,omitempty"`
	ID                 string              `json:"id,omitempty"`
	ScopeParamRequired bool                `json:"scopeParamRequired,omitempty"`
	ClientRole         bool                `json:"clientRole,omitempty"`
	ContainerID        string              `json:"containerID,omitempty"`
	Description        string              `json:"description,omitempty"`
	Attributes         map[string][]string `json:"attributes,omitempty"`
}
