/*
 * MCIAMManager API 명세서
 *
 * MCIAMManager API 명세서
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iammodels

type UserWorkspaceInfo struct {
	RoleId      string `json:"roleId,omitempty"`
	WorkspaceId string `json:"workspaceId,omitempty"`
}
