/*
 * MCIAMManager API 명세서
 *
 * MCIAMManager API 명세서
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iammodels

import (
	"github.com/gofrs/uuid"
	"mc_iam_manager/models"
)

type WorkspaceProjectMappingReq struct {
	WorkspaceId string   `json:"WorkspaceId"`
	ProjectIds  []string `json:"projectIds"`
}

func WsPjMappingreqToModels(param WorkspaceProjectMappingReq) models.MCIamWsProjectMappings {
	mappings := models.MCIamWsProjectMappings{}

	for _, pjId := range param.ProjectIds {
		mappings = append(mappings, models.MCIamWsProjectMapping{
			WsID:      uuid.FromStringOrNil(param.WorkspaceId),
			ProjectID: uuid.FromStringOrNil(pjId),
		})
	}

	return mappings
}
