/*
 * MCIAMManager API 명세서
 *
 * MCIAMManager API 명세서
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iammodels

type UserGroupReq struct {
	ID            string              `json:"Id,omitempty"`
	ParentGroupId string              `json:"parentGroupId,omitempty"`
	Name          string              `json:"groupName,omitempty"`
	Path          string              `json:"path,omitempty"`
	SubGroups     string              `json:"subGroups,omitempty"`
	Attributes    map[string][]string `json:"attributes,omitempty"`
	Access        map[string]bool     `json:"access,omitempty"`
	ClientRoles   map[string][]string `json:"clientRoles,omitempty"`
	RealmRoles    []string            `json:"realmRoles,omitempty"`
}
