/*
 * MCIAMManager API 명세서
 *
 * MCIAMManager API 명세서
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iammodels

import (
	uuid "github.com/gofrs/uuid"
	"mc_iam_manager/models"
)

type RoleTypeReq struct {
	RoleId   string `json:"roleId,omitempty"`
	RoleName string `json:"roleName,omitempty"`
	ID       string `json:"id,omitempty"`
	Type     string `json:"type,omitempty"`
}

func ConvertRoleTypeToRoleTypeInfo(roletype models.MCIamRoletype) RoleTypeInfo {
	return RoleTypeInfo{
		RoleId:   roletype.RoleID,
		RoleName: roletype.RoleName,
		ID:       roletype.ID.String(),
		Type:     roletype.Type,
	}
}

func ConvertRoleTypeReqToRoleType(roletype RoleTypeReq) models.MCIamRoletype {

	return models.MCIamRoletype{
		RoleID:   roletype.RoleId,
		RoleName: roletype.RoleName,
		ID:       uuid.FromStringOrNil(roletype.ID),
		Type:     roletype.Type,
	}
}
