package handler

import (
	"os"
)

var MCINFRAMANAGER = os.Getenv("MCINFRAMANAGER")
var MCINFRAMANAGER_APIUSERNAME = os.Getenv("MCINFRAMANAGER_APIUSERNAME")
var MCINFRAMANAGER_APIPASSWORD = os.Getenv("MCINFRAMANAGER_APIPASSWORD")

var KEYCLOAK_ADMIN = os.Getenv("KEYCLOAK_ADMIN")
var KEYCLOAK_ADMIN_PASSWORD = os.Getenv("KEYCLOAK_ADMIN_PASSWORD")
var KEYCLOAK_HOST = os.Getenv("KEYCLOAK_HOST")
var KEYCLAOK_REALM = os.Getenv("KEYCLAOK_REALM")
var KEYCLAOK_CLIENT = os.Getenv("KEYCLAOK_CLIENT")
var KEYCLAOK_CLIENT_SECRET = os.Getenv("KEYCLAOK_CLIENT_SECRET")
