package handler

import (
	"os"
)

var MCINFRAMANAGER = os.Getenv("MCINFRAMANAGER")
var MCINFRAMANAGER_APIUSERNAME = os.Getenv("MCINFRAMANAGER_APIUSERNAME")
var MCINFRAMANAGER_APIPASSWORD = os.Getenv("MCINFRAMANAGER_APIPASSWORD")

var KEYCLOAK_HOST = os.Getenv("KEYCLOAK_HOST")
var KEYCLOAK_REALM = os.Getenv("KEYCLOAK_REALM")
var KEYCLOAK_CLIENT = os.Getenv("KEYCLOAK_CLIENT")
var KEYCLOAK_CLIENT_SECRET = os.Getenv("KEYCLOAK_CLIENT_SECRET")

var USE_TICKET_VALID = os.Getenv("USE_TICKET_VALID") // 임시 티켓 처리 사용 유무
