package handler

import (
	"os"
)

var MCINFRAMANAGER = os.Getenv("MCINFRAMANAGER")
var MCINFRAMANAGER_APIUSERNAME = os.Getenv("MCINFRAMANAGER_APIUSERNAME")
var MCINFRAMANAGER_APIPASSWORD = os.Getenv("MCINFRAMANAGER_APIPASSWORD")
