package main

import (
	"context"
	"log"
	"os"
	"path/filepath"

	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	echomiddleware "github.com/labstack/echo/v4/middleware"
	"github.com/m-cmp/mc-iam-manager/config"
	"github.com/m-cmp/mc-iam-manager/handler"
	"github.com/m-cmp/mc-iam-manager/middleware"

	// "github.com/m-cmp/mc-iam-manager/model" // No longer needed directly in main
	"github.com/m-cmp/mc-iam-manager/repository"
	"github.com/m-cmp/mc-iam-manager/service"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	_ "github.com/m-cmp/mc-iam-manager/docs" // docs is generated by Swag CLI, you have to import it.
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title MC IAM Manager API
// @version 1.0
// @description MC IAM Manager API Documentation
// @host localhost:3000
// @BasePath /api/v1
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
func main() {
	// .env 파일 로드 (프로젝트 루트에서 찾도록 수정)
	envPath := filepath.Join("..", ".env")
	if err := godotenv.Load(envPath); err != nil {
		log.Printf("Warning: .env 파일을 로드하는데 실패했습니다: %v", err)
	}

	// // 데이터베이스 초기화
	// db, err := config.InitDB()
	// if err != nil {
	// 	log.Fatalf("Failed to initialize database: %v", err)
	// }
	// 데이터베이스 초기화
	dbConfig := config.NewDatabaseConfig()
	db, err := gorm.Open(postgres.Open(dbConfig.GetDSN()), &gorm.Config{})
	if err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	// Keycloak 초기화
	if err := config.InitKeycloak(); err != nil {
		log.Fatalf("Failed to initialize Keycloak: %v", err)
	}

	// Echo 인스턴스 생성
	e := echo.New()

	// 미들웨어 설정
	e.Use(echomiddleware.Logger())
	e.Use(echomiddleware.Recover())
	e.Use(echomiddleware.CORS())

	// Repository 초기화
	userRepo := repository.NewUserRepository(db, config.KC, config.KC.Client) // Pass db instance

	platformRoleRepo := repository.NewPlatformRoleRepository(db)
	workspaceRoleRepo := repository.NewWorkspaceRoleRepository(db)
	// Need PermissionRepository for MenuService
	permissionRepo := repository.NewPermissionRepository(db) // Define permissionRepo earlier

	// Service 초기화
	// Pass platformRoleRepo to NewUserService
	userService := service.NewUserService(userRepo, platformRoleRepo, config.KC, config.KC.Client)
	platformRoleService := service.NewPlatformRoleService(platformRoleRepo)
	workspaceRoleService := service.NewWorkspaceRoleService(workspaceRoleRepo)

	// 핸들러 초기화
	// Pass keycloakClient and userRepo to NewAuthHandler
	authHandler := handler.NewAuthHandler(config.KC, config.KC.Client, userRepo)
	platformRoleHandler := handler.NewPlatformRoleHandler(platformRoleService)
	workspaceRoleHandler := handler.NewWorkspaceRoleHandler(workspaceRoleService)
	userHandler := handler.NewUserHandler(userService)

	// 메뉴 핸들러 초기화 (DB 사용)
	menuRepo := repository.NewMenuRepository(db)
	// permissionRepo is already defined above, just use it
	// Need UserService for MenuService (or just UserRepository)
	// Assuming MenuService needs UserRepository directly
	menuService := service.NewMenuService(menuRepo, userRepo, permissionRepo)
	menuHandler := handler.NewMenuHandler(menuService)

	// --- Sync Platform Superadmin (Call after UserService is initialized) ---
	if err := userService.SyncPlatformAdmin(context.Background()); err != nil {
		// Log the error but continue starting the application
		log.Printf("Error during platform superadmin sync: %v", err)
	}

	// Workspace 및 Project 핸들러 초기화
	workspaceRepo := repository.NewWorkspaceRepository(db)
	projectRepo := repository.NewProjectRepository(db)
	workspaceService := service.NewWorkspaceService(workspaceRepo, projectRepo) // Pass both repos
	projectService := service.NewProjectService(projectRepo, workspaceRepo)     // Pass both repos
	workspaceHandler := handler.NewWorkspaceHandler(workspaceService)
	projectHandler := handler.NewProjectHandler(projectService)

	// 라우트 설정
	e.GET("/readyz", func(c echo.Context) error {
		return c.JSON(200, map[string]string{"status": "ok"})
	})

	// // 인증 라우트
	// e.POST("/login", authHandler.Login)
	// e.POST("/logout", authHandler.Logout)
	// e.POST("/refresh", authHandler.RefreshToken)

	api := e.Group("/api")
	// 인증 라우트
	api.POST("/auth/login", authHandler.Login)
	api.POST("/auth/logout", authHandler.Logout)
	api.POST("/auth/refresh", authHandler.RefreshToken)

	// 사용자 라우트
	api.Use(middleware.KeycloakAuthMiddleware)
	{
		api.GET("/users", userHandler.GetUsers)
		api.GET("/users/:id", userHandler.GetUserByID)
		api.GET("/users/username/:username", userHandler.GetUserByUsername)
		api.POST("/users", userHandler.CreateUser) // Admin creates enabled user
		api.PUT("/users/:id", userHandler.UpdateUser)
		api.DELETE("/users/:id", userHandler.DeleteUser)
		api.POST("/users/:id/approve", userHandler.ApproveUser) // Admin approves registration
	}

	// TODO: Add public registration route (e.g., POST /register) if needed

	// 메뉴 라우트
	api.GET("/menus", menuHandler.GetUserMenuTree)     // User-specific menu tree
	api.GET("/menus/all", menuHandler.GetAllMenusTree) // All menus tree (Admin)
	api.GET("/menus/:id", menuHandler.GetByID)
	api.POST("/menus", menuHandler.Create)
	api.PUT("/menus/:id", menuHandler.Update)
	api.DELETE("/menus/:id", menuHandler.Delete)
	api.POST("/menus/register-from-yaml", menuHandler.RegisterMenusFromYAML)
	api.POST("/menus/register-from-body", menuHandler.RegisterMenusFromBody) // YAML 본문 등록 라우트 추가

	// 플랫폼 역할 라우트
	api.GET("/platform-roles", platformRoleHandler.List)
	api.GET("/platform-roles/:id", platformRoleHandler.GetByID)
	api.POST("/platform-roles", platformRoleHandler.Create)
	api.PUT("/platform-roles/:id", platformRoleHandler.Update)
	api.DELETE("/platform-roles/:id", platformRoleHandler.Delete)

	// 워크스페이스 역할 라우트
	api.GET("/workspace-roles", workspaceRoleHandler.List)
	api.GET("/workspace-roles/:id", workspaceRoleHandler.GetByID)
	api.POST("/workspace-roles", workspaceRoleHandler.Create)
	api.PUT("/workspace-roles/:id", workspaceRoleHandler.Update)
	api.DELETE("/workspace-roles/:id", workspaceRoleHandler.Delete)

	// Workspace 라우트
	api.POST("/workspaces", workspaceHandler.CreateWorkspace)
	api.GET("/workspaces", workspaceHandler.ListWorkspaces)
	api.GET("/workspaces/name/:name", workspaceHandler.GetWorkspaceByName) // Add route for GetByName
	api.GET("/workspaces/:id", workspaceHandler.GetWorkspaceByID)
	api.PUT("/workspaces/:id", workspaceHandler.UpdateWorkspace)
	api.DELETE("/workspaces/:id", workspaceHandler.DeleteWorkspace)
	api.POST("/workspaces/:id/projects/:projectId", workspaceHandler.AddProjectToWorkspace)
	api.DELETE("/workspaces/:id/projects/:projectId", workspaceHandler.RemoveProjectFromWorkspace)

	// Project 라우트
	api.POST("/projects", projectHandler.CreateProject)
	api.GET("/projects", projectHandler.ListProjects)
	api.GET("/projects/name/:name", projectHandler.GetProjectByName) // Add route for GetByName
	api.GET("/projects/:id", projectHandler.GetProjectByID)
	api.PUT("/projects/:id", projectHandler.UpdateProject)
	api.DELETE("/projects/:id", projectHandler.DeleteProject)
	api.POST("/projects/:id/workspaces/:workspaceId", projectHandler.AddWorkspaceToProject)
	api.DELETE("/projects/:id/workspaces/:workspaceId", projectHandler.RemoveWorkspaceFromProject)

	// ... existing code ...
	// 권한 관리 API 라우트
	// Use the already initialized permissionRepo
	permissionService := service.NewPermissionService(permissionRepo)
	permissionHandler := handler.NewPermissionHandler(permissionService)
	api.POST("/permissions", permissionHandler.Create)
	api.GET("/permissions", permissionHandler.List)
	api.GET("/permissions/:id", permissionHandler.GetByID)
	api.PUT("/permissions/:id", permissionHandler.Update)
	api.DELETE("/permissions/:id", permissionHandler.Delete)
	// Updated role-permission routes to include roleType
	api.POST("/roles/:roleType/:roleId/permissions/:permissionId", permissionHandler.AssignRolePermission)
	api.DELETE("/roles/:roleType/:roleId/permissions/:permissionId", permissionHandler.RemoveRolePermission)
	api.GET("/roles/:roleType/:roleId/permissions", permissionHandler.GetRolePermissions)

	// Swagger 라우트 추가
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// 서버 시작
	port := os.Getenv("PORT")
	if port == "" {
		port = "8082"
	}
	e.Logger.Fatal(e.Start(":" + port))
}

// Helper methods to access gorm.DB from repositories (add these to respective repo files if not already present)
/*
// In repository/user_repository.go
func (r *UserRepository) DB() *gorm.DB {
	return r.db
}

// In repository/platform_role_repository.go
func (r *PlatformRoleRepository) DB() *gorm.DB {
	return r.db
}
*/
